#!/usr/bin/env bash

FILE="$0"
MYDIR=$(dirname -- "$FILE")

source "$MYDIR/shared"

if [ $# -ne 0 ]; then
	echo "${LC}Patches bedrock_server_symbols.debug to make its debugging symbols linkable$R"
	echo "${LC}Usage: ${LR}$0$R"
	exit 1
fi

set -e
if [ ! -f "$PWD/bedrock_server_symbols.debug" ]; then
	echo "${LC}This version has symbols embedded in bedrock_server directly - copying$R"
	cp "$PWD/bedrock_server" "$PWD/bedrock_server_symbols.debug"
fi
export_server_symbols "$PWD/bedrock_server_symbols.debug" "$PWD/bedrock_server_symbols_test.debug"
