#!/usr/bin/env bash

FILE="$0"
MYDIR=$(dirname -- "$FILE")

source "$MYDIR/shared"

if [ $# -ne 1 ]; then
	echo "${LC}Runs Frida tracer on a bedrock_server process$R"
	echo "${LC}Usage: ${LR}$0 ${LC}<${LY}name of executable${LC}>$R"
	exit 1
fi

(source "$PWD/python-venv/bin/activate" && python3 "$PWD/tracer.py" rw "$1") || exit 1
